# Generated by Django 4.0.3 on 2022-04-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_alter_documenttype_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='character_lengh',
            new_name='character_length',
        ),
    ]
