# Generated by Django 4.0.3 on 2022-04-08 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0004_rename_character_lengh_documenttype_character_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='static/images/avatar/default.png', upload_to='static/images/avatar/')),
                ('document_number', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.documenttype')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
